class DataBase{
  String username;
  String topic;
  String avatar;
  String image;
  String message;
  String time;
  DataBase({this.username, this.topic, this.avatar,this.image, this.message, this.time});
}

List <DataBase> dataSet = [
  DataBase(
    username: 'Rachael',
    topic: 'Drama|Action',
    time: '12:45 PM',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    image: 'https://cdn.pixabay.com/photo/2020/04/16/11/41/waterfall-5050298_960_720.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.',
  ),
  DataBase(
    username: 'Lucy',
    topic: 'Fiction|Crime',
    time: '1:40 PM',
    avatar: 'https://images.pexels.com/photos/952057/pexels-photo-952057.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2016/11/06/17/17/north-america-1803504__340.jpg',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  ),
  DataBase(
    username: 'Jason',
    topic: 'News|Entertainment',
    time: '2:02 PM',
    avatar: 'https://images.pexels.com/photos/1194412/pexels-photo-1194412.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/05/04/09/09/giraffe-5128394__340.jpg',
    message: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text.',
  ),
  DataBase(
    username: 'Lucifer',
    topic: 'Crime|Entertainment',
    time: '7:00 PM',
    avatar: 'https://images.pexels.com/photos/1448371/pexels-photo-1448371.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/09/06/22/11/neptune-5550216__340.jpg',
    message: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. ',
  ),
  DataBase(
    username: 'Becky',
    topic: 'Romance|Crime',
    time: '5:50 PM',
    avatar: 'https://images.pexels.com/photos/1070970/pexels-photo-1070970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/23/12/00/flamingo-5332314__340.jpg',
    message: 'Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? ',
  ),
  DataBase(
    username: 'Jonas',
    topic: 'Thriller|Science',
    time: '2:30 AM',
    avatar: 'https://images.pexels.com/photos/1430627/pexels-photo-1430627.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/15/17/10/ancient-5302626__340.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish.',
  ),
  DataBase(
    username: 'Maria',
    topic: 'Comedy|News',
    time: '5:35 PM',
    avatar: 'https://images.pexels.com/photos/1440399/pexels-photo-1440399.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/21/07/08/lichen-5323493__340.jpg',
    message: 'The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.',
  ),
  DataBase(
    username: 'James',
    topic: 'Adventure|Music',
    time: '12:08 AM',
    avatar: 'https://images.pexels.com/photos/1439951/pexels-photo-1439951.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/26/21/39/chicago-5344027__340.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains',
  ),
  DataBase(
    username: 'Beth',
    topic: 'Music|Games',
    time: '3:45 PM',
    avatar: 'https://images.pexels.com/photos/1292684/pexels-photo-1292684.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2019/08/15/17/56/production-4408573__340.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains',
  ),
  DataBase(
    username: 'Lisa',
    topic: 'Media|News',
    time: '5:25 PM',
    avatar: 'https://images.pexels.com/photos/1461447/pexels-photo-1461447.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/09/26/07/19/grapes-5603367__340.jpg',
    message: 'To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?',
  ),
  DataBase(
    username: 'Rachael 1',
    topic: 'Drama|Action',
    time: '12:45 PM',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    image: 'https://cdn.pixabay.com/photo/2020/04/16/11/41/waterfall-5050298_960_720.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.',
  ),
  DataBase(
    username: 'Lucy 1',
    topic: 'Fiction|Crime',
    time: '1:40 PM',
    avatar: 'https://images.pexels.com/photos/952057/pexels-photo-952057.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2016/11/06/17/17/north-america-1803504__340.jpg',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  ),
  DataBase(
    username: 'Jason 1',
    topic: 'News|Entertainment',
    time: '2:02 PM',
    avatar: 'https://images.pexels.com/photos/1194412/pexels-photo-1194412.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/05/04/09/09/giraffe-5128394__340.jpg',
    message: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text.',
  ),
  DataBase(
    username: 'Lucifer 1',
    topic: 'Crime|Entertainment',
    time: '7:00 PM',
    avatar: 'https://images.pexels.com/photos/1448371/pexels-photo-1448371.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/09/06/22/11/neptune-5550216__340.jpg',
    message: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. ',
  ),
  DataBase(
    username: 'Becky 1',
    topic: 'Romance|Crime',
    time: '5:50 PM',
    avatar: 'https://images.pexels.com/photos/1070970/pexels-photo-1070970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/23/12/00/flamingo-5332314__340.jpg',
    message: 'Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? ',
  ),
  DataBase(
    username: 'Jonas 1',
    topic: 'Thriller|Science',
    time: '2:30 AM',
    avatar: 'https://images.pexels.com/photos/1430627/pexels-photo-1430627.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/15/17/10/ancient-5302626__340.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish.',
  ),
  DataBase(
    username: 'Maria 1',
    topic: 'Comedy|News',
    time: '5:35 PM',
    avatar: 'https://images.pexels.com/photos/1440399/pexels-photo-1440399.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/21/07/08/lichen-5323493__340.jpg',
    message: 'The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.',
  ),
  DataBase(
    username: 'James 1',
    topic: 'Adventure|Music',
    time: '12:08 AM',
    avatar: 'https://images.pexels.com/photos/1439951/pexels-photo-1439951.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/26/21/39/chicago-5344027__340.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains',
  ),
  DataBase(
    username: 'Beth 1',
    topic: 'Music|Games',
    time: '3:45 PM',
    avatar: 'https://images.pexels.com/photos/1292684/pexels-photo-1292684.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2019/08/15/17/56/production-4408573__340.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains',
  ),
  DataBase(
    username: 'Lisa 1',
    topic: 'Media|News',
    time: '5:25 PM',
    avatar: 'https://images.pexels.com/photos/1461447/pexels-photo-1461447.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/09/26/07/19/grapes-5603367__340.jpg',
    message: 'To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?',
  ),
  DataBase(
    username: 'Rachael 2',
    topic: 'Drama|Action',
    time: '12:45 PM',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    image: 'https://cdn.pixabay.com/photo/2020/04/16/11/41/waterfall-5050298_960_720.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.',
  ),
  DataBase(
    username: 'Lucy 2',
    topic: 'Fiction|Crime',
    time: '1:40 PM',
    avatar: 'https://images.pexels.com/photos/952057/pexels-photo-952057.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2016/11/06/17/17/north-america-1803504__340.jpg',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  ),
  DataBase(
    username: 'Jason 2',
    topic: 'News|Entertainment',
    time: '2:02 PM',
    avatar: 'https://images.pexels.com/photos/1194412/pexels-photo-1194412.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/05/04/09/09/giraffe-5128394__340.jpg',
    message: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text.',
  ),
  DataBase(
    username: 'Lucifer 2',
    topic: 'Crime|Entertainment',
    time: '7:00 PM',
    avatar: 'https://images.pexels.com/photos/1448371/pexels-photo-1448371.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/09/06/22/11/neptune-5550216__340.jpg',
    message: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. ',
  ),
  DataBase(
    username: 'Becky 2',
    topic: 'Romance|Crime',
    time: '5:50 PM',
    avatar: 'https://images.pexels.com/photos/1070970/pexels-photo-1070970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/23/12/00/flamingo-5332314__340.jpg',
    message: 'Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? ',
  ),
  DataBase(
    username: 'Jonas 2',
    topic: 'Thriller|Science',
    time: '2:30 AM',
    avatar: 'https://images.pexels.com/photos/1430627/pexels-photo-1430627.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/15/17/10/ancient-5302626__340.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish.',
  ),
  DataBase(
    username: 'Maria 2',
    topic: 'Comedy|News',
    time: '5:35 PM',
    avatar: 'https://images.pexels.com/photos/1440399/pexels-photo-1440399.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/21/07/08/lichen-5323493__340.jpg',
    message: 'The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.',
  ),
  DataBase(
    username: 'James 2',
    topic: 'Adventure|Music',
    time: '12:08 AM',
    avatar: 'https://images.pexels.com/photos/1439951/pexels-photo-1439951.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/26/21/39/chicago-5344027__340.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains',
  ),
  DataBase(
    username: 'Beth 2',
    topic: 'Music|Games',
    time: '3:45 PM',
    avatar: 'https://images.pexels.com/photos/1292684/pexels-photo-1292684.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2019/08/15/17/56/production-4408573__340.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains',
  ),
  DataBase(
    username: 'Lisa 2',
    topic: 'Media|News',
    time: '5:25 PM',
    avatar: 'https://images.pexels.com/photos/1461447/pexels-photo-1461447.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/09/26/07/19/grapes-5603367__340.jpg',
    message: 'To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?',
  ),
  DataBase(
    username: 'Rachael 3',
    topic: 'Drama|Action',
    time: '12:45 PM',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260',
    image: 'https://cdn.pixabay.com/photo/2020/04/16/11/41/waterfall-5050298_960_720.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.',
  ),
  DataBase(
    username: 'Lucy 3' ,
    topic: 'Fiction|Crime',
    time: '1:40 PM',
    avatar: 'https://images.pexels.com/photos/952057/pexels-photo-952057.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2016/11/06/17/17/north-america-1803504__340.jpg',
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  ),
  DataBase(
    username: 'Jason 3',
    topic: 'News|Entertainment',
    time: '2:02 PM',
    avatar: 'https://images.pexels.com/photos/1194412/pexels-photo-1194412.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/05/04/09/09/giraffe-5128394__340.jpg',
    message: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn\'t anything embarrassing hidden in the middle of text.',
  ),
  DataBase(
    username: 'Lucifer 3',
    topic: 'Crime|Entertainment',
    time: '7:00 PM',
    avatar: 'https://images.pexels.com/photos/1448371/pexels-photo-1448371.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/09/06/22/11/neptune-5550216__340.jpg',
    message: 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. ',
  ),
  DataBase(
    username: 'Becky 3',
    topic: 'Romance|Crime',
    time: '5:50 PM',
    avatar: 'https://images.pexels.com/photos/1070970/pexels-photo-1070970.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/23/12/00/flamingo-5332314__340.jpg',
    message: 'Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? ',
  ),
  DataBase(
    username: 'Jonas 3',
    topic: 'Thriller|Science',
    time: '2:30 AM',
    avatar: 'https://images.pexels.com/photos/1430627/pexels-photo-1430627.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/15/17/10/ancient-5302626__340.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish.',
  ),
  DataBase(
    username: 'Maria 3',
    topic: 'Comedy|News',
    time: '5:35 PM',
    avatar: 'https://images.pexels.com/photos/1440399/pexels-photo-1440399.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/21/07/08/lichen-5323493__340.jpg',
    message: 'The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.',
  ),
  DataBase(
    username: 'James 3',
    topic: 'Adventure|Music',
    time: '12:08 AM',
    avatar: 'https://images.pexels.com/photos/1439951/pexels-photo-1439951.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/06/26/21/39/chicago-5344027__340.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains',
  ),
  DataBase(
    username: 'Beth 3',
    topic: 'Music|Games',
    time: '3:45 PM',
    avatar: 'https://images.pexels.com/photos/1292684/pexels-photo-1292684.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2019/08/15/17/56/production-4408573__340.jpg',
    message: 'On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains',
  ),
  DataBase(
    username: 'Lisa 3',
    topic: 'Media|News',
    time: '5:25 PM',
    avatar: 'https://images.pexels.com/photos/1461447/pexels-photo-1461447.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    image: 'https://cdn.pixabay.com/photo/2020/09/26/07/19/grapes-5603367__340.jpg',
    message: 'To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?',
  ),
];